/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as BankaccountLinkImport } from './routes/bankaccount.link'
import { Route as AuthSigninImport } from './routes/auth.signin'
import { Route as AuthMagiclinkConfirmationImport } from './routes/auth.magiclink.confirmation'
import { Route as AuthMagiclinkAuthenticateImport } from './routes/auth.magiclink.authenticate'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BankaccountLinkRoute = BankaccountLinkImport.update({
  id: '/bankaccount/link',
  path: '/bankaccount/link',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMagiclinkConfirmationRoute = AuthMagiclinkConfirmationImport.update({
  id: '/magiclink/confirmation',
  path: '/magiclink/confirmation',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMagiclinkAuthenticateRoute = AuthMagiclinkAuthenticateImport.update({
  id: '/magiclink/authenticate',
  path: '/magiclink/authenticate',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/bankaccount/link': {
      id: '/bankaccount/link'
      path: '/bankaccount/link'
      fullPath: '/bankaccount/link'
      preLoaderRoute: typeof BankaccountLinkImport
      parentRoute: typeof rootRoute
    }
    '/auth/magiclink/authenticate': {
      id: '/auth/magiclink/authenticate'
      path: '/magiclink/authenticate'
      fullPath: '/auth/magiclink/authenticate'
      preLoaderRoute: typeof AuthMagiclinkAuthenticateImport
      parentRoute: typeof AuthImport
    }
    '/auth/magiclink/confirmation': {
      id: '/auth/magiclink/confirmation'
      path: '/magiclink/confirmation'
      fullPath: '/auth/magiclink/confirmation'
      preLoaderRoute: typeof AuthMagiclinkConfirmationImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthMagiclinkAuthenticateRoute: typeof AuthMagiclinkAuthenticateRoute
  AuthMagiclinkConfirmationRoute: typeof AuthMagiclinkConfirmationRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthMagiclinkAuthenticateRoute: AuthMagiclinkAuthenticateRoute,
  AuthMagiclinkConfirmationRoute: AuthMagiclinkConfirmationRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/bankaccount/link': typeof BankaccountLinkRoute
  '/auth/magiclink/authenticate': typeof AuthMagiclinkAuthenticateRoute
  '/auth/magiclink/confirmation': typeof AuthMagiclinkConfirmationRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/bankaccount/link': typeof BankaccountLinkRoute
  '/auth/magiclink/authenticate': typeof AuthMagiclinkAuthenticateRoute
  '/auth/magiclink/confirmation': typeof AuthMagiclinkConfirmationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/bankaccount/link': typeof BankaccountLinkRoute
  '/auth/magiclink/authenticate': typeof AuthMagiclinkAuthenticateRoute
  '/auth/magiclink/confirmation': typeof AuthMagiclinkConfirmationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/signin'
    | '/bankaccount/link'
    | '/auth/magiclink/authenticate'
    | '/auth/magiclink/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/signin'
    | '/bankaccount/link'
    | '/auth/magiclink/authenticate'
    | '/auth/magiclink/confirmation'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/signin'
    | '/bankaccount/link'
    | '/auth/magiclink/authenticate'
    | '/auth/magiclink/confirmation'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BankaccountLinkRoute: typeof BankaccountLinkRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BankaccountLinkRoute: BankaccountLinkRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/bankaccount/link"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/signin",
        "/auth/magiclink/authenticate",
        "/auth/magiclink/confirmation"
      ]
    },
    "/auth/signin": {
      "filePath": "auth.signin.tsx",
      "parent": "/auth"
    },
    "/bankaccount/link": {
      "filePath": "bankaccount.link.tsx"
    },
    "/auth/magiclink/authenticate": {
      "filePath": "auth.magiclink.authenticate.tsx",
      "parent": "/auth"
    },
    "/auth/magiclink/confirmation": {
      "filePath": "auth.magiclink.confirmation.tsx",
      "parent": "/auth"
    }
  }
}
ROUTE_MANIFEST_END */
